"""Flash-style fused multi-head attention kernel written in Triton.

NOT VALIDATED ON GPU YET. Requires a CUDA-capable GPU and Triton (ships with
PyTorch >= 2.1 CUDA builds).

Semantics (must match the reference exactly within harness tolerances):

- Inputs are pre-split heads: ``q/k/v`` shaped ``[B, H, S, head_dim]``.
- ``scores = (Q @ K^T) * scale`` with ``scale = head_dim ** -0.5``.
- Softmax is accumulated in fp32 regardless of input dtype (matches the
  reference's fp32-stable softmax); the probability tile is cast back to the
  input dtype only for the value matmul.
- Causal: strictly upper positions (key index > query index) are masked.
- Padding: ``valid_token_mask`` (bool ``[B, S]``) marks valid keys; invalid
  key positions are masked. Output rows for invalid query positions are zeroed
  by the caller (mirroring the reference).
- All-masked rows (never generated by the harness) yield zeros, guarded with a
  ``l_i > 0`` check.

Numerical strategy: online (running-max) softmax with rescaling, fp32
accumulators, fp16/bf16 tensor-core dots, fp32 dots with ``input_precision``
"ieee" to stay close to the fp32 reference when TF32 is not desired.
"""

from __future__ import annotations

import math
from typing import Optional

import torch
import triton
import triton.language as tl


def _next_pow2(value: int) -> int:
    return 1 << (value - 1).bit_length()


@triton.jit
def _flash_attn_fwd(
    Q, K, V, Valid, Out,
    scale,
    S,
    stride_qb, stride_qh, stride_qm, stride_qd,
    stride_kb, stride_kh, stride_kn, stride_kd,
    stride_vb, stride_vh, stride_vn, stride_vd,
    stride_ob, stride_oh, stride_om, stride_od,
    stride_vb2, stride_vs,
    H: tl.constexpr,
    D: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
    CAUSAL: tl.constexpr,
    HAS_MASK: tl.constexpr,
    PRECISE: tl.constexpr,
):
    start_m = tl.program_id(0)
    bh = tl.program_id(1)
    b = bh // H
    h = bh % H

    offs_m = start_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_d = tl.arange(0, BLOCK_D)

    q_ptrs = (
        Q
        + b * stride_qb
        + h * stride_qh
        + offs_m[:, None] * stride_qm
        + offs_d[None, :] * stride_qd
    )
    q = tl.load(
        q_ptrs,
        mask=(offs_m[:, None] < S) & (offs_d[None, :] < D),
        other=0.0,
    )

    m_i = tl.full((BLOCK_M,), float("-inf"), tl.float32)
    l_i = tl.zeros((BLOCK_M,), tl.float32)
    acc = tl.zeros((BLOCK_M, BLOCK_D), tl.float32)

    for start_n in range(0, tl.cdiv(S, BLOCK_N)):
        offs_n = start_n * BLOCK_N + tl.arange(0, BLOCK_N)
        k_ptrs = (
            K
            + b * stride_kb
            + h * stride_kh
            + offs_n[None, :] * stride_kn
            + offs_d[:, None] * stride_kd
        )
        k_tile = tl.load(
            k_ptrs,
            mask=(offs_n[None, :] < S) & (offs_d[:, None] < D),
            other=0.0,
        )
        if PRECISE:
            scores = tl.dot(q, k_tile, input_precision="ieee")
        else:
            scores = tl.dot(q, k_tile)
        scores = scores * scale

        if CAUSAL:
            can_attend = offs_n[None, :] <= offs_m[:, None]
            scores = tl.where(can_attend, scores, float("-inf"))
        if HAS_MASK:
            valid = tl.load(
                Valid + b * stride_vb2 + offs_n * stride_vs,
                mask=offs_n < S,
                other=0,
            )
            scores = tl.where(valid[None, :] > 0, scores, float("-inf"))

        m_ij = tl.max(scores, axis=1)
        alpha = tl.exp(m_i - m_ij)
        p = tl.exp(scores - m_ij[:, None])
        l_i = l_i * alpha + tl.sum(p, axis=1)
        acc = acc * alpha[:, None]

        p = p.to(q.dtype)
        v_ptrs = (
            V
            + b * stride_vb
            + h * stride_vh
            + offs_n[:, None] * stride_vn
            + offs_d[None, :] * stride_vd
        )
        v_tile = tl.load(
            v_ptrs,
            mask=(offs_n[:, None] < S) & (offs_d[None, :] < D),
            other=0.0,
        )
        if PRECISE:
            acc = tl.dot(p, v_tile, acc=acc, input_precision="ieee")
        else:
            acc = tl.dot(p, v_tile, acc=acc)
        m_i = m_ij

    out = tl.where(l_i[:, None] > 0.0, acc / l_i[:, None], 0.0)
    out = out.to(q.dtype)
    o_ptrs = (
        Out
        + b * stride_ob
        + h * stride_oh
        + offs_m[:, None] * stride_om
        + offs_d[None, :] * stride_od
    )
    tl.store(
        o_ptrs,
        out,
        mask=(offs_m[:, None] < S) & (offs_d[None, :] < D),
    )


def flash_attention(
    q: torch.Tensor,
    k: torch.Tensor,
    v: torch.Tensor,
    valid_token_mask: Optional[torch.Tensor] = None,
    causal: bool = False,
    scale: Optional[float] = None,
) -> torch.Tensor:
    """Fused multi-head attention for pre-split heads.

    Args:
        q/k/v: ``[B, H, S, head_dim]`` tensors.
        valid_token_mask: optional bool ``[B, S]``; invalid key positions are
            masked (the caller zeroes invalid query rows afterwards).
        causal: mask strictly-upper (key index > query index) positions.
        scale: default ``head_dim ** -0.5`` matching the reference.

    Returns:
        ``[B, H, S, head_dim]`` attention context (same dtype as q).
    """
    if q.dim() != 4 or k.shape != q.shape or v.shape != q.shape:
        raise ValueError(f"expected [B, H, S, D] tensors, got {tuple(q.shape)}")
    batch, heads, seq_len, head_dim = q.shape
    if seq_len <= 0 or head_dim <= 0:
        raise ValueError("sequence length and head_dim must be positive")
    if scale is None:
        scale = float(head_dim) ** -0.5

    q = q.contiguous()
    k = k.contiguous()
    v = v.contiguous()
    out = torch.empty_like(q)

    has_mask = valid_token_mask is not None
    if has_mask:
        valid = valid_token_mask.to(torch.int8).contiguous()
        stride_vb2, stride_vs = valid.stride(0), valid.stride(1)
    else:
        valid = torch.empty(0, dtype=torch.int8, device=q.device)
        stride_vb2, stride_vs = 0, 0

    block_d = max(16, _next_pow2(head_dim))
    block_m = 32 if seq_len < 64 else 64
    block_n = 32 if seq_len < 64 else 64

    grid = (triton.cdiv(seq_len, block_m), batch * heads)
    precise = q.dtype == torch.float32
    _flash_attn_fwd[grid](
        q, k, v, valid, out,
        float(scale), seq_len,
        q.stride(0), q.stride(1), q.stride(2), q.stride(3),
        k.stride(0), k.stride(1), k.stride(2), k.stride(3),
        v.stride(0), v.stride(1), v.stride(2), v.stride(3),
        out.stride(0), out.stride(1), out.stride(2), out.stride(3),
        stride_vb2, stride_vs,
        H=heads, D=head_dim,
        BLOCK_M=block_m, BLOCK_N=block_n, BLOCK_D=block_d,
        CAUSAL=causal, HAS_MASK=has_mask, PRECISE=precise,
    )
    return out
